### ISSUE TITLE
Bug with component detection on gentoo with app-arch/7zip

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [an-anime-team/sleepy-launcher#1]
![screenshot](https://github.com/an-anime-team/sleepy-launcher/assets/43478602/58807498-5f1b-4f3b-95b5-f59dfc7e423d)

"Package unavailable: 7z"

I use official 7zip for linux instead of p7zip and I have the `7zz` aliased to `7z`, so I don't understand why it doesn't detect it.

If it's used for archives other than 7z, I would suggest using `atool` and the utils for required archive formats, such as `unzip` for zip.

**Comment by Mar0xy** [comment]
`p7zip` is an absolute requirement as the rust module the launchers use requires it hence why it is listed as a dep on AUR and Flatpak releases.

**Comment by JohnTheCoolingFan** [comment]
If the program is only used for command-line applications, then there is really no difference between 7zip and p7zip. But I understand now that this is not a problem of the launcher itself, so I would rather bring this to the rust module itself, thanks for clarifying.
