### ISSUE TITLE
when playing with gamepad (ds4) screen goes to sleep eventually

### ISSUE THREAD

**Issue by bleedforever** [an-anime-team/sleepy-launcher#10]
i've been using [stimulator](https://flathub.org/apps/io.github.sigmasd.stimulator) as a workaround, but it'd be great if i didn't have to!

**Comment by scgm0** [comment]
![image](https://github.com/an-anime-team/sleepy-launcher/assets/52148221/64787696-86e2-4e54-95a1-98860ba6cfc0)
Trying to turn on game mode?

**Comment by bleedforever** [comment]
oh, i didn't know gamemode does screensaver inhibiting – thanks!

**Comment by bleedforever** [comment]
oh, i didn't know gamemode does screensaver inhibiting – thanks!
