### ISSUE TITLE
Gentoo ebuild doesn't exist yet.

### ISSUE THREAD

**Issue by anh0516** [an-anime-team/sleepy-launcher#11]
The Gentoo ebuild is not available yet. Please add it when possible. In the meantime I'll just use the relesase binary. Thanks.

**Comment by JohnTheCoolingFan** [comment]
I've made and submitted a PR to add the ebuild: https://github.com/an-anime-team/gentoo-ebuilds/pull/54 and https://github.com/an-anime-team/gentoo-ebuilds/pull/55
There are three ways you can use that immediately:
1. Change the repo git url until the PR is merged or ebuild gets added
2. Copy the ebuild to a custom local repo
3. Just use `ebuild` to merge it: `sudo ebuild sleepy-launcher-1.0.1.ebuild clean install merge`, don't forget to also add it to the `@world`: `sudo emerge --noreplace games-misc/sleepy-launcher`

I use this ebuild currently, generated via pycargoebuild and added fields using other launchers as an example.
