### ISSUE TITLE
ZZZ seems to use different domains to upload telemetry

### ISSUE THREAD

**Issue by AngelSherry** [an-anime-team/sleepy-launcher#16]
When I' m running ZZZ and open OpenSnitch GUI ( a interface of a firewall called OpenSnitch ), I noticed that the game it's uploading telemetry to these two new domains ` apm-log-upload-os.hoyoverse.com` and `zzz-log-upload-os.hoyoverse.com`.

![螢幕快照 2024-07-19 07-09-51](https://github.com/user-attachments/assets/f00857ae-0a11-41f7-86f1-b45294350bc3)

And on hosts file of my system, the launcher had added 
```
0.0.0.0 log-upload-os.hoyoverse.com
0.0.0.0 overseauspider.yuanshen.com
```
but there is no ` apm-log-upload-os.hoyoverse.com` and `zzz-log-upload-os.hoyoverse.com` on it.

Then I added these two domains to hosts manually and restarted the game, it seems everything is okay and I don't get banned.

**Comment by krypt0nn** [comment]
Thanks for the report. I will add these new domains to the block list in the next update.

**Comment by LarveyOfficial** [comment]
Did these get added yet @krypt0nn ?

**Comment by krypt0nn** [comment]
No, the app was not updated. Feels wrong to release a patch with 2 changed lines.

**Comment by krypt0nn** [comment]
Fixed in https://github.com/an-anime-team/sleepy-launcher/pull/21.
