### ISSUE TITLE
Not enough space when installed in a sysmlink folder

### ISSUE THREAD

**Issue by Ezorp** [an-anime-team/sleepy-launcher#18]
Hi, I tried to install the sleepy-launcher through the AUR package `sleepy-launcher-bin` . on the first install popup, I selected a folder which is a system link to my hard drive and when I try to download the game, I get a not enough space error.

"""
No free space available for specified path: "/home/elouan/Games/sleepy-launcher" (requires 160.44 GB, available 71.77 GB)
"""
![Selection_007](https://github.com/user-attachments/assets/bcec6053-eaf4-4657-9caf-23fe4ee03fc6)

![image](https://github.com/user-attachments/assets/5adb215c-17ed-4dad-bde2-f8a21a6c5ade)

System :
- Arch Linux
- Ryzen 7 5800 X
- RX 7900GRE
- 32GB of RAM
- 500GB NVME (/)
- 3TB HDD (/mnt/hdd) with a syslink /home/elouan/Games/ -> /mnt/hdd/elouan/home/Games

How to reproduce :
- Have the / disk with less than 160 GB free space and a sysmlink folder to a disk with enough free space.
- Install the launcher
- On the install path, select the folder on the bigger disk
- On the main menu, click on the download Button

Expected behavior :

The launcher install the game as it has enough space.

**Comment by krypt0nn** [comment]
Known, will not be fixed, use the launcher's config file instead.
