### ISSUE TITLE
fedora missing dependencies command

### ISSUE THREAD

**Issue by Kapongoboy** [an-anime-team/sleepy-launcher#4]
The missing dependencies screen provides the command `sudo dnf install git xdelta p7zip libwebp`, but the program will notify that `dwebp` can't be found. The `dwebp` binary is included in the `libwebp-tools` package for Fedora 40, and installing it allows the installation to continue successfully.

**Comment by krypt0nn** [comment]
Fixed in mainline: https://github.com/an-anime-team/an-anime-game-launcher/commit/b7bfda5a8572f56308b08f00532aebeee780cf50

Will be a part of all future updates.
